# Generated by Django 5.2.8 on 2025-12-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_rating_movie_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='likes',
        ),
    ]
